version: "3.8"

services:
  django-files:
    image: ghcr.io/django-files/django-files:${VERSION:?err}
    env_file: ${ENV_FILE:?err}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${STACK_NAME?err}.rule=Host(`${TRAEFIK_HOST?err}`)"
        - "traefik.http.routers.${STACK_NAME}.entrypoints=https"
        - "traefik.http.routers.${STACK_NAME}.tls=true"
        - "traefik.http.services.${STACK_NAME}.loadbalancer.server.port=80"
        #- "traefik.http.routers.${STACK_NAME}.tls.certresolver=le"
    volumes:
      - media_dir:/data/media
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true

volumes:
  media_dir:
