name: "Docker Stack Deploy"

on:
  workflow_dispatch:
#    inputs:
#      tags:
#        description: 'Tags: comma,separated'
#        required: true
#        default: 'latest'

env:
  CONFIG_FILE: "services/shane/df-shane/df.cssnr.env"

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Checkout Service Configs"
        uses: actions/checkout@v3
        with:
          repository: hosted-domains/service-configs
          ref: master
          path: service-configs
          sparse-checkout: ${CONFIG_FILE}
          sparse-checkout-cone-mode: false
          ssh-key: ${{ secrets.SERVICE_CONFIGS_KEY }}

      - name: "Debug"
        run: |
          ls -lah
          echo -----
          ls -lah service-configs

      - name: "Docker Stack Deploy"
        uses: cssnr/stack-deploy-action@master
        env:
          ENV_FILE: "service-configs/${{ env.CONFIG_FILE }}"
        with:
          host: ${{ secrets.DOCKER_HOST }}
          user: ${{ secrets.DOCKER_USER }}
          pass: ${{ secrets.DOCKER_PASS }}
          port: ${{ secrets.DOCKER_PORT }}
          name: "df-shane"
          file: "docker-compose-swarm.yaml"
          env_file: "${{ env.ENV_FILE }}"
          ssh_key: "${{ secrets.DOCKER_SSH_KEY }}"
